language: python

python: "2.7"

before_install:
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


# command to install dependencies
install:
  - easy_install -U pip
  - pip install PyYAML argparse
  - pip install catkin_pkg ros_buildfarm rosdistro nose coverage
  - pip install yamllint
  - pip install unidiff
  - pip install rosdep
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform

# command to run tests
script:
  - nosetests -s --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_rosdistro_1f62d74788_0
  - python -m properform Push 47.88.50.110:15554 asdf_rosdistro_1f62d74788_0 ./profile_rosdistro_1f62d74788_0
  - yamllint */

 #2017-08-12 17:16:01 modified at 0